# Generated by Django 5.0.6 on 2024-05-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesData',
        ),
    ]
