# Generated by Django 5.0.6 on 2024-05-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
