# Generated by Django 5.0.6 on 2024-05-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_content_notification_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='read',
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='No Title', max_length=255),
        ),
    ]
