# Generated by Django 5.0.6 on 2024-06-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
