# Generated by Django 5.0.6 on 2024-06-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_student_department_student_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
