# Generated by Django 5.0.6 on 2024-06-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_student_department_alter_student_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
