# Generated by Django 5.0.6 on 2024-10-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_btc_dash_ethereum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btc',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dash',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ethereum',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
