# Generated by Django 5.0.6 on 2024-10-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_btc_balance_alter_dash_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btc',
            name='balance',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='dash',
            name='balance',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='ethereum',
            name='balance',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
