# Generated by Django 5.0.6 on 2025-01-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_alter_invest_plan_alter_invest_spent_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='profit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
